# Generated by Django 4.1.4 on 2022-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sale_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='units_sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sale',
            field=models.IntegerField(),
        ),
    ]
