# Generated by Django 4.1.4 on 2022-12-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_sale_price_alter_customer_units_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sale_price',
        ),
    ]
