# Generated by Django 4.1.4 on 2022-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customer_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='available_stock_after_sale',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_no_of_sale',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sale_amount',
            field=models.IntegerField(default=None),
        ),
    ]
