# Generated by Django 4.1.4 on 2022-12-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_product_id_customer_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
