# Generated by Django 4.1.4 on 2022-12-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_product_name_customer_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
