# Generated by Django 4.1.4 on 2022-12-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customer_product_id_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.product', to_field='product_name'),
        ),
    ]
