# Generated by Django 4.1.4 on 2022-12-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customer_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
