# Generated by Django 4.1.4 on 2022-12-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_customer_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.product'),
        ),
    ]
