# Generated by Django 4.1.4 on 2022-12-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customer_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_sale_amount',
        ),
    ]
