# Generated by Django 4.1.4 on 2022-12-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_sale_available_stock_after_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='available_stock_after_sale',
        ),
    ]
