# Generated by Django 4.1.4 on 2022-12-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_sale_available_stock_after_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining_stock',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sale_amount',
            field=models.IntegerField(default=None),
        ),
    ]
