# Generated by Django 4.1.4 on 2022-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_remaining_stock_sale_total_sale_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_sale_amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='remaining_stock',
            field=models.IntegerField(),
        ),
    ]
