# Generated by Django 4.1.4 on 2022-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_sale_total_sale_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_sale_amount',
            field=models.IntegerField(default=None),
        ),
    ]
