# Generated by Django 4.1.4 on 2022-12-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_sale_total_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='api.product'),
        ),
    ]
