# Generated by Django 4.1.4 on 2022-12-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_sale_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_sale_amount',
        ),
    ]
