# Generated by Django 4.1.4 on 2022-12-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_sale_total_sale_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
