# Generated by Django 4.1.4 on 2022-12-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_product_name_customer_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='product_id',
            new_name='product',
        ),
    ]
