# Generated by Django 4.1.4 on 2022-12-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_product_customer_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='selling_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='profits',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sale_amount',
            field=models.IntegerField(default=None),
        ),
    ]
