# Generated by Django 4.1.4 on 2022-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_sale_profits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='profits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
