# Generated by Django 4.1.4 on 2022-12-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_sale_profits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_no_of_sale',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sale_amount',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
