# Generated by Django 4.1.4 on 2022-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_sale_total_no_of_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_sale_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
